### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rupakhetibinit** [Anuj-Gupta4/open-news-api-backend#2]
# Roadmap Done
- [x]  removed cache

# Roadmap Remaining
- [x]  implement tags for articles like National, Sports, Fashion, Finance, Politics, Other News
- [x]  implement basic toggle from admin panel for published/draft articles (default is draft)

**Comment by AmanGiri007** [comment]
Tags Implemented

**Comment by rupakhetibinit** [comment]
@AmanGiri007 From what I have these are the tags [National, Sports, Fashion, Finance, Politics, Other News]. But what you implemented was a search feature? I don't think headlines will let us distinguish between tags. 

Example if the headline is "Nepali team goes to Ireland to play cricket". This headline is strictly sports but the word "sports" never appears in the headline. This is a good feature for searching articles but terrible for getting a particular type of news through tags.

**Comment by Anuj-Gupta4** [comment]
finished
